name: sound_machines
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_storage: ^11.2.3
  freezed_annotation: ^2.2.0
  cloud_firestore: ^4.8.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  shared_preferences: ^2.1.1
  google_fonts: ^4.0.0
  rxdart: ^0.27.7
  loading_animations: ^2.2.0
  google_sign_in: ^6.1.2
  font_awesome_flutter: ^10.4.0
  freezed: ^2.3.5
  dio: ^5.2.0
  open_filex: ^4.3.2
  image_picker: ^0.8.7+5
  dropdown_button2: ^2.1.3
  just_audio: ^0.9.34
  audioplayers: ^4.1.0

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - Assets/
    - Assets/skip_15_next.png
    - Assets/skip_15_prev.png