// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADyCyizU5UzXCbHmqKtEUxImr9rZxlReg',
    appId: '1:506946621228:web:c3ac6f528eec40feed2689',
    messagingSenderId: '506946621228',
    projectId: 'soundmachines-1964a',
    authDomain: 'soundmachines-1964a.firebaseapp.com',
    storageBucket: 'soundmachines-1964a.appspot.com',
    measurementId: 'G-GS6PPXVDHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Ae2G0A0NDxO-UsNkgvhp70ltzAUabxI',
    appId: '1:506946621228:android:6425a7decfa764baed2689',
    messagingSenderId: '506946621228',
    projectId: 'soundmachines-1964a',
    storageBucket: 'soundmachines-1964a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1PUZN1PX3p8CkBoYXBYv6-oBfcSgZSmo',
    appId: '1:506946621228:ios:614239c61a8c48a9ed2689',
    messagingSenderId: '506946621228',
    projectId: 'soundmachines-1964a',
    storageBucket: 'soundmachines-1964a.appspot.com',
    iosClientId: '506946621228-mdq9jooqj4h49q87n2kth9b8mjun3ku7.apps.googleusercontent.com',
    iosBundleId: 'com.example.soundMachines',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1PUZN1PX3p8CkBoYXBYv6-oBfcSgZSmo',
    appId: '1:506946621228:ios:9f908a10fa13382ded2689',
    messagingSenderId: '506946621228',
    projectId: 'soundmachines-1964a',
    storageBucket: 'soundmachines-1964a.appspot.com',
    iosClientId: '506946621228-0u5momouvlab8e1ctgnqra08u90rfmqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.soundMachines.RunnerTests',
  );
}
